server:
  error:
    include-message: always
spring:
  datasource:
    password: alma
    url: jdbc:postgresql://localhost:5432/LanguageLearn
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
